### ISSUE TITLE
error when using knockout time series data

### ISSUE THREAD

**Issue by masastat** [AtteAalto/BINGO#1]
Thank you for a great tool!

I am trying to use BINGO with knockout time series data, but I found that BINGO gives an error if the last index gene is knocked out.

For example, 

```matlab
X = [1 2 3; 4 5 6];
clear('data')
data.ts = {X};
data.ko = {[2]};
[data,state,parameters]=BINGO_init(data);
[~,chain,~,state,stats]=BINGO(data,state,parameters);
```

the last line `[~,chain,~,state,stats]=BINGO(data,state,parameters);` gives an following error.

```matlab
>> [~,chain,~,state,stats]=BINGO(data,state,parameters);
Error using .*
Matrix dimensions must agree.

Error in BINGO (line 231)
        KC = chol(KM+1/q(i)*((KNM'*(d'.*KNM))) + 1e-5*eye(M));
```

I'm new to MATLAB, so I might be doing something wrong.
Also, I'm using Matlab R2020a, which is the only one possible in my environment, so it might be the cause.

I would appreciate it if you would help me.

**Comment by AtteAalto** [comment]
Hello!

Thanks for pointing this out. The code has now been fixed. Note that in your example, there is only one time series, and one gene is knocked out. In this case, it is not possible to infer links in or out from the ko'd gene. Therefore that gene could as well be omitted from the data. The method now excludes genes that are knocked out in all time series.

There was also another bug that was appearing when the last gene on the list was knocked out. This was fixed as well.
